coverage:
  status:
    project:
      default:
        # No overall test coverage threshold is enforced for the project.
        target: auto
    patch:
      default:
        # Set a constant diff hit target of 70%. 
        # This is the test coverage that new code must achieve.
        target: 70%
