coverage:
  status:
    project:
      default:
        # Overall test coverage threshold must be 70% for the project.
        target: 70%
    patch:
      default:
        # Set a constant diff hit target of 70%. 
        # This is the test coverage that new code must achieve.
        target: 70%
