from gemini import Gemini


class LLM:
    def __init__(self, llm=Gemini()):
        self.llm = llm

    def generate_response(self, user_prompt):
        """Returns a response generated by the llm."""
        prompt1 = (
            f"Study the existing market of the company {user_prompt} in a few points"
        )
        response1 = self.llm.get_llm_response(prompt1)
        prompt2 = f"simulate three future customer profiles for {user_prompt}"
        response2 = self.llm.get_llm_response(prompt2)

        response = ""
        response += response1
        response += "\n\n"
        response += response2
        return response
