import os
from dotenv import load_dotenv
import google.generativeai as genai


class Gemini:
    """API for Gemini.

    Methods
    -------
        get_llm_response(prompt):
            Returns the response to the given prompt.
    """

    def __init__(self):
        self.__GEMINI_API_KEY = self.__load_key()
        self.__ai_model = self.__configure_ai()

    def __load_key(self):
        load_dotenv()
        return os.getenv("GEMINI_API_KEY")

    def __configure_ai(self):
        genai.configure(api_key=self.__GEMINI_API_KEY)
        return genai.GenerativeModel("gemini-1.5-flash")

    def get_llm_response(self, prompt: str) -> str:
        """Returns the response to the given prompt generated by Gemini"""
        response = self.__ai_model.generate_content(prompt)
        return response.text
