name: CI

on:
  push:
    branches:
      - workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
      # Set the directory where Poetry is installed
      - working-directory: llm-api-testing/
        run: pip install poetry
      - name: Install dependencies
      - working-directory: llm-api-testing/
        run: poetry install --no-root
      - name: Run tests
        run: poetry run pytest
